import '@a1rth/css-normalize'
import './styles/index.scss'
import '@/features/preloader.js'
import '@/features/hero-typing.js'
import '@/features/scroll-to-top.js'
import '@/features/scroll-reveal.js'
import '@/features/toggle-theme.js'